@host = http://localhost:5229

GET {{host}}/openapi/v1.json
Accept: application/json

### SPENDING CATEGORIES ###

GET {{host}}/api/spendingcategories/1
Accept: application/json
###
DELETE  {{host}}/api/spendingcategories/1
Accept: application/json
###
POST {{host}}/api/spendingcategories
Content-Type: application/json

{
  "name": "Fun"
}
###
PUT {{host}}/api/spendingcategories/2
Content-Type: application/json

{
  "name": "",
  "description": "Food and household items2"
}

###
GET  {{host}}/api/spendingcategories?take=1&skip=1
Accept: application/json

### ACCOUNTS ###

GET {{host}}/api/transactionsource/1
Accept: application/json

###
GET  {{host}}/api/transactionsource?take=1&skip=0
Accept: application/json

###
POST {{host}}/api/transactionsource
Content-Type: application/json

{
  "name": "TEST123",
  "ownerId": 1
}


### TRANSACTIONS ###

GET {{host}}/api/financialtransactions/1
Accept: application/json

###
GET  {{host}}/api/financialtransactions?take=5&skip=0&transactionSourceId=1
Accept: application/json

### AUTOCOMPLETE ###
GET  {{host}}/api/autocomplete/transactionsource/1
Accept: application/json

###

GET  {{host}}/api/autocomplete/financialaccount?take=5&skip=0&search=Hannah
Accept: application/json
