@host = http://localhost:5229

GET {{host}}/openapi/v1.json
Accept: application/json

### SPENDING CATEGORIES ###

GET {{host}}/api/spendingcategories/1
Accept: application/json
###
DELETE  {{host}}/api/spendingcategories/1
Accept: application/json
###
POST {{host}}/api/spendingcategories
Content-Type: application/json
{
  "name": "Fun",
}
###
PUT {{host}}/api/spendingcategories/2
Content-Type: application/json
{
  "name": ""
  "description": "Food and household items2"
}
###
POST  {{host}}/api/spendingcategories/list
Content-Type: application/json
Accept: application/json
{
    "skip": 0,
    "take": 50
}

### ACCOUNTS ###

GET {{host}}/api/financialaccounts/1
Accept: application/json

###
POST  {{host}}/api/financialaccounts/list
Content-Type: application/json
Accept: application/json

{
    "skip": 0,
    "take": 50
}

###
POST {{host}}/api/financialaccounts
Content-Type: application/json

{
  "name": "Chase's CB Credit"
}


### TRANSACTIONS ###

GET {{host}}/api/financialtransactions/1
Accept: application/json

###
POST  {{host}}/api/financialtransactions/list
Content-Type: application/json
Accept: application/json

{
    "skip": 0,
    "take": 50
}

### AUTOCOMPLETE ###
GET  {{host}}/api/autocomplete/financialaccount/1
Accept: application/json

###

POST  {{host}}/api/autocomplete/financialaccount
Content-Type: application/json
Accept: application/json

{
    "skip": 0,
    "take": 50,
    "search": ""
}
