@host = http://localhost:5229

GET {{host}}/openapi/v1.json
Accept: application/json

###

GET {{host}}/api/spendingcategories/2
Accept: application/json

###

DELETE  {{host}}/api/spendingcategories/1
Accept: application/json

###

POST {{host}}/api/spendingcategories
Content-Type: application/json

{
  "name": "Groceries",
  "description": "For food"
}

###

PUT {{host}}/api/spendingcategories/2
Content-Type: application/json

{
  "description": "Food and household items2"
}

###

POST  {{host}}/api/spendingcategories/list
Content-Type: application/json
Accept: application/json

{
    "skip": 0,
    "take": 50,
    "filter": {
        "nameContains": "d"
    }
}
