@host = http://localhost:5229

GET {{host}}/openapi/v1.json
Accept: application/json

###

GET {{host}}/api/spendingcategories/2
Accept: application/json

###

DELETE  {{host}}/api/spendingcategories/1
Accept: application/json

###

POST {{host}}/api/spendingcategories
Content-Type: application/json

{
  "name": "Groceries",
  "description": "Food and household items"
}

###

PUT {{host}}/api/spendingcategories
Content-Type: application/json

{
  "id": 1,
  "description": "Food and household items2"
}
